// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT6EB4uJi7QdKKLAUe_uRS_8js46djnJ4',
    appId: '1:163464121541:web:8d72576c186750c43ab4ac',
    messagingSenderId: '163464121541',
    projectId: 'hci-traffic-light',
    authDomain: 'hci-traffic-light.firebaseapp.com',
    storageBucket: 'hci-traffic-light.appspot.com',
    measurementId: 'G-CPXKJ244QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6wO_psq7OcUPlM4GeJwUavTHQ4SIB8g',
    appId: '1:163464121541:android:5458df89b2ded53a3ab4ac',
    messagingSenderId: '163464121541',
    projectId: 'hci-traffic-light',
    storageBucket: 'hci-traffic-light.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtVUuDK735gfFpxUDaaYfwntqsrP3XKsA',
    appId: '1:163464121541:ios:e632f518a9850c153ab4ac',
    messagingSenderId: '163464121541',
    projectId: 'hci-traffic-light',
    storageBucket: 'hci-traffic-light.appspot.com',
    iosBundleId: 'com.example.classLight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtVUuDK735gfFpxUDaaYfwntqsrP3XKsA',
    appId: '1:163464121541:ios:e632f518a9850c153ab4ac',
    messagingSenderId: '163464121541',
    projectId: 'hci-traffic-light',
    storageBucket: 'hci-traffic-light.appspot.com',
    iosBundleId: 'com.example.classLight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT6EB4uJi7QdKKLAUe_uRS_8js46djnJ4',
    appId: '1:163464121541:web:b74b7b280bfee2053ab4ac',
    messagingSenderId: '163464121541',
    projectId: 'hci-traffic-light',
    authDomain: 'hci-traffic-light.firebaseapp.com',
    storageBucket: 'hci-traffic-light.appspot.com',
    measurementId: 'G-6DX8MNZ9SB',
  );

}